# Generated by Django 4.1.7 on 2023-03-16 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('theme_pic', models.FileField(blank=True, null=True, upload_to='themes/')),
                ('start_time', models.DateTimeField(verbose_name='Start time of the theme:')),
                ('end_time', models.DateTimeField(verbose_name='End time of the field: ')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='current_round',
            new_name='current_round_overall',
        ),
        migrations.AddField(
            model_name='question',
            name='genre_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='current_genre_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='round',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='question',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.genre'),
        ),
    ]
